
//侧边栏二级分类的国家类型介绍，所有图片为本人制作，文案自拟

var attr = [
  {
    idx:'',
    src:require('../../public/img/sideBar/0.png'),
    info:'联合国成员国',
    intro:'联合国是二战战后建立，完全由主权国家组成的国际机构。截至当前，共有正式会员国193个，观察国两个（巴勒斯坦国和梵蒂冈）'
  },
  {
    idx:'天',
    src:require('../../public/img/sideBar/1.png'),
    info:'天主教国家',
    intro:'继承自西罗马公教，于11世纪和拜占庭帝国东正教产生分裂。天主教拥有教皇和宗教领土，即坐落于罗马城中的梵蒂冈城国'
  },
  {
    idx:'新',
    src:require('../../public/img/sideBar/2.png'),
    info:'基督新教国家',
    intro:'16世纪由神父马丁路德倡议，为了脱离罗马教廷压迫而产生的新宗教派别，新教推崇信徒自行参悟和理解教义。我国称为基督教'
  },
  {
    idx:'伊',
    src:require('../../public/img/sideBar/3.png'),
    info:'伊斯兰教国家',
    intro:'由默罕默德于7世纪创立，伊斯兰教借照了一些天主教的世界观。穆罕穆德去世后，教徒就哈里发阿里的即位问题分裂为逊尼派和什叶派'
  },
  {
    idx:'东',
    src:require('../../public/img/sideBar/4.png'),
    info:'东正教国家',
    intro:'罗马帝国于公元476年覆灭。君士坦丁堡不再认可罗马教廷的合法性，并因教义分歧产生对立。斯拉夫民族是东正教的主要受众'
  },
  {
    idx:'佛',
    src:require('../../public/img/sideBar/5.png'),
    info:'佛教国家',
    intro:'诞生于公元前6世纪南亚地区，与基督教(含天主教)/伊斯兰教并称为世界三大宗教，由于不主张干涉世俗政治，因而思想更具温和性'
  },
  {
    idx:'非',
    src:require('../../public/img/sideBar/6.png'),
    info:'世俗国家',
    intro:'所在国宗教多元化，因某些历史/政治原因弱化了宗教影响。不存在具有绝对地位和数量优势/能够干涉世俗生活与政治的教派'
  },
  {
    idx:'内',
    src:require('../../public/img/sideBar/7.png'),
    info:'内陆国家',
    intro:'所在国不具有任何领海，且被邻国领土所包围的国家。由于里海是咸水湖，与其毗邻的沿海国家，也属于内陆国'
  },
  {
    idx:'岛',
    src:require('../../public/img/sideBar/8.png'),
    info:'岛屿国家',
    intro:'指完全在岛屿之上，没有大陆领土的国家。澳大利亚由于是整块大陆，不属于岛国；英国虽然有多个大陆殖民地，但本土仍属于岛国'
  },
  {
    idx:'发',
    src:require('../../public/img/sideBar/9.png'),
    info:'发达国家',
    intro:'指具有较高人类发展指数，平均收入，工业化标准的相对先进国家。因为欧盟作为一个经济整体，高发展指数的小国可以忽略工业标准'
  },
  {
    idx:'不',
    src:require('../../public/img/sideBar/11.png'),
    info:'最不发达国家',
    intro:'人类发展指数低下，同时识字率、社会生产力、经济抗风险能力和普通民众的营养健康水平难以达到国际最低标准的国家'
  },
  {
    idx:'中',
    src:require('../../public/img/sideBar/10.png'),
    info:'发展中国家',
    intro:'世界上绝大多数国家都是发展中国家，某些资源出口国，虽然实现了高人均收入，但其工业化水平仍处于发展中国家行列'
  },
  {
    idx:'地',
    src:require('../../public/img/sideBar/12.png'),
    info:'地区性强国',
    intro:'所在国的军事或经济具有一定的地区或国际影响力，不包含五个常任理事国。朝韩日虽然与中俄为邻，但仍属于地区性强国'
  },{
    idx:'英',
    src:require('../../public/img/sideBar/15.png'),
    info:'英语国家',
    intro:'英语几乎作为世界所有国家的通用语言。此处仅包含把英语作为第一语言的国家，这些国家几乎都有作为英国殖民地的经历'
  },{
    idx:'德',
    src:require('../../public/img/sideBar/16.png'),
    info:'德语国家',
    intro:'欧盟第一母语，主要由具有日耳曼民族的国家使用，由于战败国身份，德国丧失了海外殖民地的控制权，德语也仅分布于欧洲大陆'
  },
  {
    idx:'西',
    src:require('../../public/img/sideBar/18.png'),
    info:'西班牙语国家',
    intro:'作为大航海时代发现新大陆的国家。西班牙人得以占领美洲的绝大部分领土并建立殖民地，西语因此在南北美洲被广泛使用'
  },
  {
    idx:'法',
    src:require('../../public/img/sideBar/17.png'),
    info:'法语国家',
    intro:'除欧洲本土，法语使用国多分布于非洲西部和中部。这源于19世纪英法对非洲的全面殖民，法国至今都和这些地区保持着密切联系'
  },
  {
    idx:'黑',
    src:require('../../public/img/sideBar/19.png'),
    info:'黑非洲国家',
    intro:'主要构成是尼格罗人（又称黑种人）的国家，此处仅限非洲南部的大部分地区。不包含因黑奴贸易等历史原因产生的其他大洲国家'
  },
  {
    idx:'阿',
    src:require('../../public/img/sideBar/14.png'),
    info:'阿拉伯国家',
    intro:'以阿拉伯语为官方语言，且主要民族构成为阿拉伯人的国家。包括中东部分地区和北非，阿拉伯国家普遍信仰伊斯兰教'
  },
  {
    idx:'巴',
    src:require('../../public/img/sideBar/21.png'),
    info:'巴尔干国家',
    intro:'位于欧亚交界的小亚细亚和巴尔干半岛国家。由于其敏感的地理位置和民族/宗教/语言/政治的多重对立，素有欧洲火药桶之称'
  },
  {
    idx:'牙',
    src:require('../../public/img/sideBar/20.png'),
    info:'葡萄牙语国家',
    intro:'葡萄牙是世界上最早开辟欧亚航道的国家，并借此建立了庞大的世界贸易网络和最早的一批殖民地，其中巴西是葡萄牙语的主要使用国'
  },
  {
    idx:'苏',
    src:require('../../public/img/sideBar/25.png'),
    info:'苏联加盟国',
    intro:'前苏联成立于1917年，由东斯拉夫三国、波罗的海三国、高加索三国、中亚五国和摩尔多瓦共15个国家组成，于1991年解体'
  },
  {
    idx:'永',
    src:require('../../public/img/sideBar/22.png'),
    info:'永久中立国',
    intro:'声明不论任何时期，均奉行外交中立政策的国家。该类国家通常战略位置不关键，不参与其他国之间的战争或敏感军事行动'
  },
  {
    idx:'未',
    src:require('../../public/img/sideBar/26.png'),
    info:'未建交国家',
    intro:'因所在国不建立任何外交关系(不丹)或违背一个中国原则未和中国建立外交关系的主权国家，多为拉美地区和大洋洲国家'
  }
]

export {
  attr
}