
//一个为了打包更快的假数据

var flags = [
  {
    id: 195,
    type: 1,
    name: '卡塔尔',
    fullname: '卡塔尔国',
    ename: 'Qatar',
    city: '多哈',
    people: 2640000,
    land: '亚洲',
    area: 11580,
    time: 1971,
    gdp: 1920,
    per: 69026,
    dens: 176,
    attr: '阿伊中',
    code: "白红三2无",
    place: '西亚',
    flag:require('../../public/img/flag/KTE.png'),
    badge:require('../../public/img/badge/KTE1.png'),
    lang: ['阿拉伯语'],
    partvalue: [25,13.5,12.1,10.8,10,8.6,5.6,4.8,9.6],
    part: ['印度人','尼泊尔人','卡塔尔人','孟加拉人','菲律宾人','埃及人','斯里兰卡人','巴基斯坦人','其他族群'],
    belief: ['伊斯兰教']
  },{
    id: 194,
    type: 1,
    name: '哈萨克斯坦',
    fullname: '哈萨克斯坦共和国',
    ename: 'Kazakhstan',
    city: '努尔苏丹',
    people: 18400000,
    land: '亚洲',
    area: 2727300,
    time: 1991,
    gdp: 1447,
    per: 8480,
    dens: 6.8,
    attr: '苏中伊内',
    code: "蓝黄1日动单字",
    place: '中亚',
    flag: require('../../public/img/flag/HSK.png'),
    badge: require('../../public/img/badge/HSK1.png'),
    lang: ['哈萨克语','俄语'],
    partvalue: [68.48,20.61,12.91],
    part: ['哈萨克族','俄罗斯族','其他族群'],
    belief: ['伊斯兰教','基督新教']
  },{
    id: 193,
    type: 1,
    name: '斯里兰卡',
    fullname: '斯里兰卡民主社会主义共和国',
    ename: 'Sri Lanka',
    city: '科伦坡',
    people: 21440000,
    land: '亚洲',
    area: 65600,
    time: 1991,
    gdp: 889,
    per: 4102,
    dens: 305,
    attr: '中岛佛',
    code: "红绿黄四1动器单",
    place: '南亚地区',
    flag: require('../../public/img/flag/SLLK.png'),
    badge: require('../../public/img/badge/SLLK1.png'),
    lang: ['僧伽罗语','泰米尔语'],
    partvalue: [73.8,18,8.3],
    part: ['僧伽罗族','泰米尔族','摩尔人'],
    belief: ['佛教','印度教']
  },{
    id: 192,
    type: 1,
    name: '马来西亚',
    fullname: '马来西亚联邦',
    ename: 'Malaysia',
    city: '吉隆坡',
    people: 32660000,
    land: '亚洲',
    area: 330350,
    time: 1957,
    gdp: 3543.5,
    per: 11239,
    dens: 92,
    attr: '中伊',
    code: "蓝白黄红四条月星5",
    place: '东南亚',
    flag: require('../../public/img/flag/MLXY.png'),
    badge: require('../../public/img/badge/MLXY1.png'),
    lang: ['马来语'],
    partvalue: [69.3,22.8,6.9],
    part: ['原住民','华人','印度人'],
    belief: ['伊斯兰教']
  },{
    id:191,
    type: 1,
    name: '文莱',
    fullname: '文莱达鲁萨兰国',
    ename: 'Brunei',
    city: '斯里巴加湾',
    people: 422700,
    land: '亚洲',
    area: 5765,
    time: 1984,
    gdp: 135.7,
    per: 31628,
    dens: 72,
    attr: '中岛伊',
    code: "黑白黄红三字器不月4人单",
    place: '东南亚',
    flag: require('../../public/img/flag/WL.png'),
    badge: require('../../public/img/badge/WL1.png'),
    lang: ['马来语'],
    partvalue: [66.3,11.2,3.4,2.3,16.8],
    part: ['马来人','华人','原住民','印度人','其他族群'],
    belief: ['伊斯兰教']
  },{
    id: 190,
    type: 1,
    name: '亚美尼亚',
    fullname: '亚美尼亚共和国',
    ename: 'Armenia',
    city: '埃里温',
    people: 3062500,
    land:'亚洲',
    area: 29800,
    time: 1991,
    gdp: 121.03,
    per: 3952,
    dens: 109,
    place: '西亚',
    code: "红蓝黄条8无",
    attr: '苏中内新',
    flag: require('../../public/img/flag/YMNY.png'),
    badge: require('../../public/img/badge/YMNY1.png'),
    lang: ['亚美尼亚语'],
    partvalue: [93.3, 6.7],
    part: ['亚美尼亚族','其他族群'],
    belief: ['基督新教']
  },{
    id: 189,
    type: 1,
    name: '乌兹别克斯坦',
    fullname: '乌兹别克斯坦共和国',
    ename: 'Uzbekistan',
    city: '塔什干',
    people: 33375800,
    land: '亚洲',
    area: 448900,
    time: 1991,
    gdp: 721.96,
    per: 2163,
    dens: 75,
    attr: '苏中内伊',
    code: "蓝红白绿条5月多",
    place: '中亚',
    flag: require('../../public/img/flag/WZBK.png'),
    badge: require('../../public/img/badge/WZBK1.png'),
    lang: ['乌兹别克语'],
    partvalue: [80,5.5,4,3,5],
    part: ['乌孜别克族','俄罗斯族','塔吉克族','哈萨克族','其他族群'],
    belief: ['伊斯兰教']
  },{
    id: 188,
    type: 1,
    name: '阿塞拜疆',
    fullname: '阿塞拜疆共和国',
    ename: 'Azerbaijan',
    city: '巴库',
    people: 10000000,
    land: '亚洲',
    area: 86600,
    time: 1991,
    gdp: 469.4,
    per: 4721,
    dens: 118,
    attr: '苏内中伊',
    code: "蓝红绿白条8月星",
    place: '西亚',
    flag: require('../../public/img/flag/ASBJ.png'),
    badge: require('../../public/img/badge/ASBJ1.png'),
    lang: ['阿塞拜疆语'],
    partvalue: [90.6,2.2,1.8,1.5,3.9],
    part: ['阿塞拜疆族','列兹根族','俄罗斯族','亚美尼亚族','其他族群'],
    belief: ['伊斯兰教']
  },{
    id: 187,
    type: 1,
    name: '蒙古',
    fullname: '蒙古国',
    ename: 'Mongolia',
    city: '乌兰巴托',
    people: 3200000,
    land: '亚洲',
    area: 1566500,
    time: 1991,
    gdp: 130.1,
    per: 4104,
    dens: 2,
    attr: '内中佛',
    code: "红蓝黄条3单",
    place: '东亚',
    flag: require('../../public/img/flag/MG.png'),
    badge: require('../../public/img/badge/MG1.png'),
    lang: ['蒙古语'],
    partvalue: [85,7,4.6,3.4],
    part: ['喀尔喀蒙古族','哈萨克族','通古斯族','其他民族'],
    belief: ['佛教']
  },{
    id: 186,
    type: 1,
    name: '朝鲜',
    fullname: '朝鲜民主主义人民共和国',
    ename: 'North Korea',
    city: '平壤',
    people: 25550000,
    land: '亚洲',
    area: 122800,
    time: 1948,
    gdp: 307,
    per: 1204,
    dens: 198,
    attr: '地中非',
    code: "红白蓝圆5条星",
    place: '东亚',
    flag: require('../../public/img/flag/CX.png'),
    badge: require('../../public/img/badge/CX1.png'),
    lang: ['朝鲜语'],
    partvalue: [100],
    part: ['朝鲜族'],
    belief: []
  },{
    id: 185,
    type: 1,
    name: '东帝汶',
    fullname: '东帝汶民主共和国',
    ename: 'Timor-Leste',
    city: '帝力',
    people: 1296000,
    land: '亚洲',
    area: 14920,
    time: 2002,
    gdp: 25.81,
    per: 2036,
    dens: 129,
    attr: '不岛牙天',
    code: "黑黄红白三32星",
    place: '东南亚',
    flag: require('../../public/img/flag/DDW.png'),
    badge: require('../../public/img/badge/DDW1.png'),
    lang: ['天主教'],
    partvalue: [78,20,2],
    part: ['原住民','印尼人','华人'],
    belief: ['天主教']
  }
]

export {
  flags
}